[project]
name = "comp0034-wk3"
version = "1.0.0"
description = "COMP0034 Week 3 coding activities"
dependencies = [
    "flask",
    "flask-sqlalchemy"
]

[build-system]
requires = ["setuptools", "setuptools-scm",]
build-backend = "setuptools.build_meta"
